# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' 
    - name: Check docker compose version
      run: docker-compose --version
    - name: Run docker images and start test
      run: | 
        docker-compose up -d 
        npm test
      working-directory: ./services
    - name: Stop docker images
      run: docker-compose down
      working-directory: ./services
